/*
 * This source file was generated by the Gradle 'init' task
 */
package sequencer;

import org.apache.camel.main.Main;

public class App {
    public void setupSequencer() {
        Main main = new Main();
        try {
            System.out.println("Started RFQ Sequencer.");
            main.setAppName("RFQ Sequencer");
            main.configure().addRoutesBuilder(new RfqSequencerRoute());
            main.run();
            System.err.println("Stopped RFQ Sequencer.");
        } catch (Exception e) {
            System.err.println("Error starting RFQ Sequencer: " + e.getMessage());
            main.stop();
            e.printStackTrace();
        }
    }

    public static void main(String[] args) {
        new App().setupSequencer();
    }
}
